# Generated by Django 5.0.2 on 2024-03-05 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recette',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='membre.recette'),
            preserve_default=False,
        ),
    ]
