# Generated by Django 5.0.2 on 2024-03-05 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0002_ingredient_recette'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='recette',
        ),
        migrations.AddField(
            model_name='recette',
            name='photo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='membre.photo'),
            preserve_default=False,
        ),
    ]
