# Generated by Django 5.0.2 on 2024-03-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0003_remove_photo_recette_recette_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='fichier',
            field=models.ImageField(upload_to='static/image_recette'),
        ),
    ]
