# Generated by Django 5.0.2 on 2024-03-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='fichier',
            field=models.ImageField(upload_to='static/image_recette'),
        ),
    ]
