# Generated by Django 5.0.3 on 2024-03-11 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0007_alter_photo_fichier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoris',
            name='recette',
        ),
        migrations.AlterField(
            model_name='favoris',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoris',
            name='recette',
            field=models.ManyToManyField(to='membre.recette'),
        ),
    ]
