# Generated by Django 5.0.2 on 2024-03-18 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0011_remove_recette_accomplie_recette_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette_accomplie',
            name='recette',
        ),
        migrations.AddField(
            model_name='recette_accomplie',
            name='recette',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='membre.recette'),
            preserve_default=False,
        ),
    ]
