# Generated by Django 5.0.2 on 2024-03-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0012_remove_recette_accomplie_recette_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recette_accomplie',
        ),
    ]
